pipeline:
  app:
    image: node:8
    commands:
      - npm install
      - npm run build
    when:
      branch: dev

  deploy:
    image: drillster/drone-rsync
    hosts: [ "serverkb.strelka.com" ]
    key: ${PRIVATE_KEY}
    source: ./Build
    target: ~/SaratovBuild

