pipeline:
  app:
    image: node:8
    commands:
      - npm install
      - npm run build

  deploy:
      image: appleboy/drone-scp
      host: serverkb.strelka.com
      username: saratov
      target: ~/SaratovApp/Build_${DRONE_BUILD_NUMBER}
      source: ./Build/*
      secrets: [scp_key]
      when:
        status: success
