pipeline:
  app:
    image: docker
    commands:
      - docker build -t tmshv/saratov:latest -t tmshv/saratov:build-${DRONE_BUILD_NUMBER} .
      - docker save -o saratov-docker_container${DRONE_BUILD_NUMBER}.tar tmshv/saratov:build-${DRONE_BUILD_NUMBER}
    when:
      branches: [master, dev]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  scp:
    image: appleboy/drone-scp
    host: saratov.tmshv.com
    username: master
    target: ~/Saratov
    source: saratov-docker_container${DRONE_BUILD_NUMBER}.tar
    secrets: [scp_key]
