pipeline:
  app:
    image: node:8
    commands:
      - npm install
      - npm run build
    when:
      branch: dev

  deploy:
      image: appleboy/drone-scp
      host: serverkb.strelka.com
      username: saratov
      target: ~/SaratovApp/Build
      source: ./Build
      secrets: [scp_key]
