export const attributeTranslation = {
	name: "имя",
	zone: "Зона",
	width: "Ширина (макс)",
	depth: "Глубина (макс)",
	"angle lot": "Глубина углового участка (макс)",
	max_area: "Площадь (макс)",
	min_area: "Площадь (мин)",
	lot_dencity: "Доля застроенности (макс)",
	mm_dencity: "Доля территории участка, занимаемая плоскостной автостоянкой (макс)",
	green_dencity: "Доля озеленения на участке (мин)",
	redline: "Отступ линии застройки от красной линии (макс)",
	redline_dencity: "Доля застроенности участка по уличному фронту (мин)",
	redline_facade: "Длина фасада по уличному фронту (макс)",
	min_dist_car: "Отступ плоскостных автостоянок от красной линии (мин)",
	utilities_max_dist: "Отступ зданий и сооружений  вспомогательных видов разрешенного использования от красной линии (макс)",
	height: "Высота застройки (макс)",
	street_height: "Высота до карниза / парапета вдоль фронта улицы (макс)",
	cap_type: "Допустимый тип кровли здания, выходящего на уличный фронт",
	cap: "Уклон кровли здания, выходящего на уличный фронт (макс)",
	cap_k: "Отступ плоскости верхних этажей от линии застройки, м / уклон угловой плоскости пространственного конверта",
	glass_dencity: "Доля площади проемов к глухой поверхности стены (мин)",
	window_prportion: "Пропорции окон (высота к ширине)*",
	wall_width: "Ширина простенка (макс)",
	window_height: "Высота окна (макс)",
	window_step: "Расстояния между горизонт. осями (макс)",
	window_pattern: "Расстояния между вертикальными осями (макс)",
	consol: "Выступ консольных элементов здания из плоскости фасада (макс)",
	consol_height: "Высота просвета между консольно выступающими элементами здания и поверхностью земли (мин)",
	consol_area: "Доля плоскости выступающих элементов фасада (макс)",
	facade_area: "Доля глухой поверхности фасада, окрашенной в основной цвет (мин)",
	colour: "Палитра основных цветов фасада",
	material: "Материалы",
	start_floor_height: "Высота (мин)",
	entrance_height: "Уровень входа (макс)",
	hole_proportion: "Пропорции проемов (высота к ширине)*",
	border_height: "Высота ограждений (макс)",
	border_transparancy: "Прозрачность ограждений (мин)",
	entrance_public: "Входы (для нежилых помещений)*",
	entrance_live: "Входы (для жилых помещений)*",
	colour_start_floor: "Палитра основных цветов фасада (цвет первого этажа не должен отличаться от цвета фасада, выходящего на уличный фронт)",
	material_start_floor: "Материалы",
	column_step: "Шаг колонн (макс)",
	S_lot: "Площадь участка",
	S_b: "Общая площадь застройки",
	S_footprint: "Площадь подошвы здания",
	S_mm: "Площадь плоскостных парковок на участке",
	S_green: "Площадь озеленения",
	status: "Статус территории",
};

export const attributeUnits = {
	width: "м",
	depth: "м",
	"angle lot": "м",
	max_area: "м²",
	min_area: "м²",
	lot_dencity: "%",
	mm_dencity: "%",
	green_dencity: "%",
	redline: "м",
	redline_dencity: "%",
	redline_facade: "м",
	min_dist_car: "м",
	utilities_max_dist: "м",
	height: "м",
	street_height: "м",
	cap: "°",
	cap_k: "°",
	glass_dencity: "%",
	wall_width: "м",
	window_height: "м",
	window_step: "м*",
	window_pattern: "м*",
	consol: "м",
	consol_height: "м",
	consol_area: "%",
	facade_area: "%",
	start_floor_height: "м*",
	entrance_height: "м*",
	border_height: "м",
	border_transparancy: "%",
	column_step: "м",
	S_lot: "м²",
	S_b: "м²",
	S_footprint: "м²",
	S_mm: "м²",
	S_green: "м²",
};

export const groups = [
	{
		"name": "ОСНОВНЫЕ ТЭП",
		"attributes": [
			"S_lot",
			"S_b",
			"S_footprint",
			"S_mm",
			"S_green",
			"status",
		]
	},

	{
		"name": "ТРЕБОВАНИЯ К УЧАСТКАМ",
		"attributes": [
			"width",
			"depth",
			"angle lot",
			"max_area",
		]
	},

	{
		"name": "ТРЕБОВАНИЯ К РАСПОЛОЖЕНИЮ ОБЪЕКТОВ НА УЧАСТКЕ",
		"attributes": [
			"min_area",
			"lot_dencity",
			"mm_dencity",
			"green_dencity",
			"redline",
			"redline_dencity",
			"redline_facade",
			"min_dist_car",
		]
	},

	{
		"name": "ТРЕБОВАНИЯ К ОБЪЕМНО-ПРОСТРАНСТВЕННЫМ ХАРАКТЕРИСТИКАМ ЗАСТРОЙКИ",
		"attributes": [
			"utilities_max_dist",
			"height",
			"street_height",
			"cap_type",
			"cap",
		]
	},

	{
		"name": "ТРЕБОВАНИЯ К ФАСАДАМ ЗДАНИЙ, ВЫХОДЯЩИМ НА УЛИЧНЫЙ ФРОНТ (КРОМЕ ПЕРВОГО ЭТАЖА)",
		"footnote": "* неприменимо для индивидуальных жилых домов",
		"attributes": [
			"cap_k",
			"glass_dencity",
			"window_prportion",
			"wall_width",
			"window_height",
			"window_step",
			"window_pattern",
			"consol",
			"consol_height",
			"consol_area",
			"facade_area",
			"colour",
			"material",
		]
	},

	{
		"name": "ТРЕБОВАНИЯ К ПЕРВЫМ ЭТАЖАМ ЗДАНИЙ, ВЫХОДЯЩИМ НА УЛИЧНЫЙ ФРОНТ",
		"footnote": "* неприменимо для индивидуальных жилых домов",
		"attributes": [
			"start_floor_height",
			"entrance_height",
			"hole_proportion",
			"border_height",
			"border_transparancy",
			"glass_dencity",
			"entrance_public",
			"entrance_live",
			"colour_start_floor",
			"material_start_floor",
			"column_step",
		]
	}
];